pip:update:
  do: exec
  command: pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
pip:install:
  do: exec
  desc: Always access PyPI with no-cache-dir. This may help if the cache got stuck.
  command: pip install -U --no-cache-dir <<packages>>

jupyter:ls:
  do: exec
  command: jupyter kernelspec list

conda:ls:
  do: exec
  command: conda info --env
conda:batch:
  do: exec
  desc: running a certain command across all conda env. excluding base
  command: conda info --env | grep -v -E '#|base' - | cut -d' ' -f1 | xargs -i -n1 -P1 bash -c ". $(which activate) {} && <<command>>"
conda:batch:ch:
  do: exec
  desc: similar to conda:batch, but restricted to env. with <<channel>> in the name, and install packages from that channel
  command: conda info --env | grep -v -E '#|base' - | grep <<channel(defaults,intel)>> - | cut -d' ' -f1 | xargs -i -n1 -P1 bash -c ". $(which activate) {} && conda install -c <<channel>> <<packages>> -y"
conda:batch:rm:
  do: exec
  desc: remove all conda environments
  command: conda info --env | grep -v -E '#|base' - | cut -d' ' -f1 | xargs -i -n1 -P1 bash -c "$(which conda) remove -n {} --all -y"
conda:batch:rm:inteldefaults:
  do: exec
  desc: remove all intel/defaults environments
  command: conda info --env | grep -v -E '#|base' - | grep -E '(defaults|intel)' - | cut -d' ' -f1 | xargs -i -n1 -P1 bash -c "$(which conda) remove -n {} --all -y"
conda:batch:update:all:
  do: exec
  desc: update all conda environments
  command: mamba info --json | python -c 'import json; import sys; list(map(print, json.load(sys.stdin)["envs"]))' | grep -v '^/Applications' | xargs -n1 mamba update --all -y -p
conda:ch:
  do: exec
  desc: set a highest priority channel
  command: conda config --prepend channels <<channel(defaults,intel)>> && cat ~/.condarc
conda:update:
  do: exec
  desc: update conda
  command: mamba update -n base --all
conda:env:update:
  do: exec
  desc: update current conda environment
  command: mamba update --all
conda:clean:
  do: exec
  desc: conda cleanup all
  command: mamba clean --all -y

pip:dev:
  do: exec
  desc: pip install current directory in editable mode
  command: pip install -e .

# macOS brew
brew:update:
  do: exec
  command: (while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &; brew update && brew update && brew upgrade && brew cleanup && brew doctor)
brew:ls:
  do: exec
  command: brew leaves
brew:lsv:
  do: exec
  command: brew ls --versions $(brew leaves)
brew:cleanup:
  do: exec
  desc: force cleanup and clear cache
  command: brew cleanup -s && rm -rf $(brew --cache)
brew:linux:ca:nersc:
  do: exec
  desc: ln ca cert on NERSC
  command: ln -s /etc/ssl/certs ~/.linuxbrew/etc/openssl && ln -s /var/lib/ca-certificates/ca-bundle.pem ~/.linuxbrew/etc/openssl/cert.pem && ~/.linuxbrew/opt/openssl/bin/c_rehash
# linux apt
apt:update:
  do: exec
  desc: update ubuntu
  command: (while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &; sudo apt -y update && sudo apt -y upgrade && sudo apt -y autoremove)
apt:upgrade:
  do: exec
  desc: upgrade ubuntu to next release
  command: (while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &; sudo apt update -y && sudo apt dist-upgrade -y && sudo apt install update-manager-core -y && do-release-upgrade)
apt:ls:
  do: exec
  desc: list installed apt packages
  command: |
    comm -23 <(apt-mark showmanual | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u)

# arch
gpg:aurutils:
  do: exec
  desc: trust gpg key of aurutils
  command: gpg --recv-keys DBE7D3DD8C81D58D0A13D0E76BC26A17B9B7018A

pacman:refresh:mirror:
  do: exec
  desc: refresh pacman mirror list
  command: rate-mirrors arch | sudo tee /etc/pacman.d/mirrorlist

pacman:refresh:mirror:upgrade:
  do: exec
  desc: refresh pacman mirror list and then upgrade
  command: |
    rate-mirrors arch | sudo tee /etc/pacman.d/mirrorlist
    yay -Syyu --sudoloop --nomakepkgconf --noanswerclean --noanswerdiff --noansweredit --noanswerupgrade --nocleanmenu --nodiffmenu --noeditmenu --noupgrademenu --norebuild --noredownload --overwrite

pacman:upgrade:
  do: exec
  desc: yay upgrade all
  command: yay -Syu --sudoloop --nomakepkgconf --noanswerclean --noanswerdiff --noansweredit --noanswerupgrade --nocleanmenu --nodiffmenu --noeditmenu --noupgrademenu --norebuild --noredownload --overwrite
pacman:rm:
  do: exec
  desc: remove a package using yay
  command: yay -Rs <<package>>
pacman:rm:orphan:
  do: exec
  desc: removing orphans and their configuration files (run this recursively until none)
  command: yay -Rns $(yay -Qtdq)
pacman:ls:
  do: exec
  desc: List all explicitly installed packages
  command: pacman -Qe
pacman:ls:local:
  do: exec
  desc: List all foreign packages (typically manually downloaded and installed or packages removed from the repositories a.k.a. AUR)
  command: pacman -Qm
pacman:ls:native:
  do: exec
  desc: List all native packages (installed from the sync database)
  command: pacman -Qn
pacman:ls:native:explicit:
  do: exec
  desc: List all explicitly installed native packages (i.e. present in the sync database) that are not direct or optional dependencies
  command: pacman -Qent
pacman:ls:date:
  do: exec
  desc: List installed packages by date
  command: expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort
pacman:ls:dependencies:
  do: exec
  desc: List dependencies of a given package
  command: pacman -Qi <<package>>
pacman:search:
  do: exec
  desc: search package (ERE supported)
  command: yay -Ss '<<package>>'
pacman:clean:
  do: exec
  desc: remove all but 1 past version of cache of installed packages
  command: sudo pacman -Sc && paccache --remove --keep 1

aur:install:
  do: exec
  desc: install packages from AUR
  command: aursync <<package>>
aur:upgrade:
  do: exec
  desc: upgrade packages form AUR
  command: aursync -cu

# go
go:update:
  do: exec
  desc: update all go packages
  command: go get -u all

# jupyter
jupyter:install:
  do: exec
  desc: install a jupyter lab extension
  command: jupyter labextension install <<extension>>
jupyter:update:
  do: exec
  desc: update all packages
  command: jupyter labextension update --all
jupyter:ls:
  do: exec
  desc: list installed jupyter lab extensions
  command: jupyter labextension list

# vscode
code:ls:
  do: exec
  desc: list vscode installed extensions
  command: code --list-extensions 2>/dev/null

xcode:
  do: exec
  desc: install xcode command line tools.
  command: xcode-select --install && sudo xcodebuild -license accept

port:update:
  do: exec
  desc: update macports
  command: (while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &; sudo port selfupdate && sudo port upgrade outdated)
port:cleanup:
  do: exec
  desc: cleanup macports
  command: sudo port -f clean --all all && sudo port -f uninstall inactive
port:cutleaves:
  do: exec
  desc: remove "leaves" in macports
  command: sudo port_cutleaves -b
port:ls:
  do: exec
  desc: list installed packages
  command: port installed
port:check:x86_64:
  do: exec
  desc: list all macports package that's x86_64
  command: find /opt/local/bin -exec file {} + | grep -A 1 x86_64

rhel:check:subscription:
  do: exec
  desc: check if valid RHEL subscription exists
  command: sudo subscription-manager list --installed
rhel:update:
  do: exec
  desc: update packages on RHEL
  command: sudo dnf update
rhel:ls:
  do: exec
  desc: list user installed packages on RHEL
  command: dnf history userinstalled

linux:update:terminal:
  do: exec
  desc: choose the default terminal emulator when Ctrl-Alt-T is pressed.
  command: sudo update-alternatives --config x-terminal-emulator

install:reload-browser:
  do: exec
  desc: install reload-browser for entr
  command: (cd ~/.local/bin; wget http://eradman.com/entrproject/scripts/reload-browser; chmod +x reload-browser)
